require:
  - rubocop-rails

inherit_from: .rubocop_todo.yml

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0
  SuggestExtensions: false
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'bin/**/*'
    - 'vendor/**/*'
    - 'node_modules/**/*'
    - 'lib/tasks/auto_annotate_models.rake'

Style/Documentation:
  Enabled: false

Metrics/ClassLength:
  Max: 500

Metrics/ModuleLength:
  Max: 200

Metrics/MethodLength:
  Max: 50

Metrics/BlockLength:
  Max: 100

Metrics/AbcSize:
  Max: 35

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/PerceivedComplexity:
  Max: 10

Layout/LineLength:
  Max: 150

Rails/OutputSafety:
  Enabled: false

Lint/MissingSuper:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: always