name: Ruby Gem

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby: ["3.1.6", "3.2.3", "3.3.0"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: false

      - name: Bundle install
        run: |
          bundle config set frozen false
          bundle install

    # - name: Run tests
    #   run: bundle exec rake

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2"
          bundler-cache: false

      - name: Bundle install
        run: |
          bundle config set frozen false
          bundle install

      - name: Run rubocop
        run: bundle exec rubocop
